##virtualhost configuration /etc/nginx/conf.d/app.conf
server {
  listen ${PORT} ssl;
  server_name ${app_name}.example.com; # if you use port based virtual hosting, you can use _ as a wildcard or permanent name
  http2 on;

  ssl_certificate     /etc/nginx/ssl/cert.crt;
  ssl_certificate_key /etc/nginx/ssl/key.key;
  error_page 497 https://$host:$server_port$request_uri;

  # --- SECURITY: SSL Hardening ---
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305";
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 20m;
  ssl_stapling off;
  ssl_stapling_verify off;

  # --- SECURITY: Security Headers ---
  add_header Strict-Transport-Security "max-age=31536000" always;
  add_header X-Frame-Options "SAMEORIGIN" always;           # Prevents Clickjacking
  add_header X-Content-Type-Options "nosniff" always;       # Prevents MIME-sniffing
  add_header X-XSS-Protection "1; mode=block" always;       # XSS Filter
  #add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';" always;

  # Enable micro-cache
  proxy_cache microcache;
  proxy_cache_valid 200 10s;
  proxy_cache_valid 404 1s;

  # Cache bypass for dynamic requests
  proxy_cache_bypass $cookie_session;
  add_header X-Cache-Status $upstream_cache_status;

  # LOGGING CONFIGURATION
  access_log /var/log/nginx/${app_name}_access.log main;
  error_log  /var/log/nginx/${app_name}_error.log warn; 

  location / {
  proxy_pass https://${upstream_name};

  # --- SSL BACKEND VERIFICATION ---
  proxy_ssl_verify off; #if you have a valid certificate on the backend, you can enable this and specify the trusted certificate
  #proxy_ssl_trusted_certificate /etc/nginx/ssl/cert.crt; 

  # Standard Headers
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  # --- PERFORMANCE: Enable Upstream Keepalive,Buffers and HealthCheck ---
  proxy_http_version 1.1; # HTTP 1.1 is required for keepalive
  proxy_set_header Connection ""; # Clear the connection headers
  proxy_connect_timeout 3s; # timeouts
  proxy_read_timeout 60s;

  # Buffers
  proxy_buffer_size 16k;
  proxy_buffers 8 16k;
  proxy_busy_buffers_size 32k;
  proxy_buffering on;

  # health-check failure handling
  proxy_next_upstream error timeout http_500 http_502 http_503 http_504; 
 }
}