#caching configuration /etc/nginx/conf.d/cache.conf
proxy_cache_path /var/cache/nginx/microcache levels=1:2 keys_zone=microcache:50m max_size=2g inactive=60m use_temp_path=off;
proxy_cache_lock on; # prevents multiple concurrent requests from hitting the backend for same miss
proxy_cache_lock_timeout 5s;