#caching configuration /etc/nginx/conf.d/cache.conf
# If /var/cache/nginx/microcache not available, create it with: mkdir -p /var/cache/nginx/microcache && chown www-data:nginx /var/cache/nginx/microcache for 
# RHEL based distros, or chown www-data:www-data for Debian based distros. 
# Adjust permissions as needed for your security requirements.
proxy_cache_path /var/cache/nginx/microcache levels=1:2 keys_zone=microcache:50m max_size=2g inactive=60m use_temp_path=off;
# proxy_cache_lock prevents multiple concurrent requests from hitting the backend for same miss
proxy_cache_lock on;
proxy_cache_lock_timeout 5s;