##virtualhost upstream configuration /etc/nginx/conf.d/app1_upstream.conf
upstream ${upstream_name}{
   #ip_hash; #session persistence based on client IP address
   hash $remote_addr consistent; #session persistence based on client IP address
   server 192.168.58.10:${PORT} max_fails=3 fail_timeout=5s;
   server 192.168.58.11:${PORT} max_fails=3 fail_timeout=5s;
   server 192.168.58.12:${PORT} max_fails=3 fail_timeout=5s;
   server 172.20.0.120:${PORT};
   keepalive 32; #Keep 32 idle connections open to backend, configure as your tarffic
}